# Numpy

In [9]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
i=np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
o=np.ones((3,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#3d array
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
print(a.ndim)

3


In [16]:
print(a[-1,1,2])

12


In [18]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [19]:
print(arr[4:])

[5 6 7]


In [20]:
print(arr[:4])

[1 2 3 4]


In [22]:
print(arr[::2])

[1 3 5 7]


In [23]:
print(arr[1:5:2])

[2 4]


In [24]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [25]:
print(arr[:2,2])

[3 8]


In [26]:
arr=np.array([1.2,2.1,3.1])
newArr=arr.astype('i')

print(newArr)

[1 2 3]


In [27]:
arr=np.array([1,6,0,3,0,4])
boolArr=arr.astype(bool)
print(boolArr)

[ True  True False  True False  True]


In [30]:
arr=np.array([1,2,3,4])

x=arr.copy()
y=arr.view()

arr[0]=1760

print("copy:",x)
print("view:",y)

print(x.base)
print(y.base)

copy: [1 2 3 4]
view: [1760    2    3    4]
None
[1760    2    3    4]


In [33]:
#shape, reshape

arr=np.array([[1,2,3,4,5,12],[6,7,8,9,10,11]])
print(arr.shape)

(2, 6)


In [32]:
newArr=arr.reshape(3,4)
print(newArr)

[[ 1  2  3  4]
 [ 5 12  6  7]
 [ 8  9 10 11]]


In [34]:
arr=np.array([1,2,3,4,5,6,7,8])
nArr=arr.reshape(2,2,-1)
print(nArr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
#flattening Array

fArr=nArr.reshape(-1)
print(fArr)

[1 2 3 4 5 6 7 8]


In [36]:
arr=np.array([1,2,3,4,5,6,7,8])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8


In [37]:
arr=np.array([[1,2,3,4,5,12],[6,7,8,9,10,11]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
12
6
7
8
9
10
11


In [38]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in a:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [39]:
for x in np.nditer(a):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [42]:
#iterating as string

for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [43]:
for idx,x in np.ndenumerate(a):
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [44]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])

arr=np.concatenate((a1,a2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [45]:
arr=np.concatenate((a1,a2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
arr=np.array([1,2,3,4,5,6,7,8,9])
newArr=np.array_split(arr,3)
print(newArr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [47]:
arr=np.array([1,0,3,4,0,6,0,8,0])
print(np.where(arr==0))


(array([1, 4, 6, 8], dtype=int64),)


In [48]:
print(np.sort(arr))

[0 0 0 0 1 3 4 6 8]


In [49]:
arr=np.array([10,20,30,40,50])
x=[True,False,True,False,False]

newArr=arr[x]
print(newArr)

[10 30]
