# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)

1.18.5


#### 3. Create a null vector of size 10

In [3]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
print("%d bytes" % (arr.size * arr.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [5]:
arr1=np.zeros(10)
arr1[4]=1
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [14]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [12]:
arr=np.array([1,3,5,6,7])
revarr=arr[::-1]
print(revarr)

[7 6 5 3 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
b=np.arange(0,9).reshape(3,3)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [19]:
a=np.array([1,2,0,0,4,0])
print(np.where(a!=0))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [20]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [21]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.1184854  0.88335417 0.70972512]
  [0.81755415 0.38887738 0.7292027 ]
  [0.33421001 0.528185   0.42796644]]

 [[0.28807821 0.92612696 0.38587624]
  [0.59638786 0.75985691 0.22335221]
  [0.2755702  0.89211964 0.92147145]]

 [[0.21396549 0.75694869 0.57040379]
  [0.12424605 0.15955329 0.04094906]
  [0.26795419 0.32203312 0.96802773]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
arr=np.random.random((10,10))
print(arr)

x=np.sort(arr)
print(x[0,0])
print(x[9,9])

[[0.36301452 0.60905952 0.17775372 0.51382602 0.11619681 0.1156162
  0.036398   0.98503574 0.33338706 0.89644609]
 [0.5206546  0.95601297 0.98992872 0.01471943 0.04856416 0.4246103
  0.975495   0.27206999 0.99611014 0.86931239]
 [0.40860214 0.52722788 0.68169082 0.90331352 0.05314582 0.72782023
  0.80748351 0.67378969 0.63498158 0.17897558]
 [0.54734617 0.34837237 0.97678863 0.92608959 0.17287887 0.05948929
  0.824017   0.39432042 0.45006649 0.08514919]
 [0.29429611 0.80598493 0.69104671 0.54950762 0.67796987 0.40887351
  0.13793754 0.7753879  0.74170569 0.24558927]
 [0.44055266 0.25987568 0.13336109 0.01851358 0.24438464 0.75167887
  0.95170109 0.42150715 0.10583571 0.06938652]
 [0.87465388 0.2594102  0.51928523 0.70972179 0.60959066 0.2658252
  0.62538864 0.59522947 0.59020787 0.4709822 ]
 [0.80424479 0.45360978 0.67650012 0.57769681 0.11437767 0.18599088
  0.70376322 0.00664383 0.989396   0.99365065]
 [0.68950853 0.82762793 0.06734986 0.41140008 0.27603746 0.97987344
  0.29244478 0.

#### 14. Create a random vector of size 30 and find the mean value

In [25]:
arr=np.random.random(30)
print(np.mean(arr))


0.4820538771109756


#### 15. Create a 2d array with 1 on the border and 0 inside

In [30]:
n=int(input())

a=np.zeros(n*n).reshape(n,n)

for i in range(len(a)):
    for j in range(len(a[i])):
        if(i==0 or j==0 or i==(n-1) or j==(n-1)):
            a[i][j]=1

print(a)



10
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [3]:
import numpy as np
a=np.random.random((3,3))

print(a)
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print("---------------------------------------")
print(a)          


[[0.97837346 0.9535753  0.52271745]
 [0.91327523 0.89334396 0.49069542]
 [0.27332741 0.92002177 0.92862407]]
---------------------------------------
[[0.         0.         0.         0.         0.        ]
 [0.         0.97837346 0.9535753  0.52271745 0.        ]
 [0.         0.91327523 0.89334396 0.49069542 0.        ]
 [0.         0.27332741 0.92002177 0.92862407 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression?

In [11]:

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
a=np.zeros(5*5).reshape(5,5)
for i in range(len(a)):
    for j in range(len(a[i])):
        if(i-1==j):
            a[i][j]=i
print(a)            


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
a=np.zeros(8*8).reshape(8,8)

a[1::2,::2] = 1
a[::2,1::2] = 1

print(a)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [12]:
import numpy as np

arr=np.random.random((6,7,8))

c=0
for idx,x in np.ndenumerate(arr):
    
    if(c==100):
        print(idx)
    c+=1    

(1, 5, 4)
